version: '3.8'

services:
  backend:
    build:
      context: ./backend
      args:
        DB_HOST: ${DB_HOST}
        DB_PORT: ${DB_PORT}
        DB_DATABASE: ${DB_DATABASE}
        DB_USERNAME: ${DB_USERNAME}
        DB_PASSWORD: ${DB_PASSWORD}
    container_name: backend
    environment:
      BOT_TOKEN: ${BOT_TOKEN}
      CHAT_ID: ${CHAT_ID}
      TELES3_FILEID_LENGTH: ${TELES3_FILEID_LENGTH}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
    ports:
      - "9275:80"
    restart: always

  frontend:
    build:
      context: ./frontend
      args:
        # VITE_BACKEND_API should be something like https://backend.example.com
        # It should include https:// or http:// and no trailing backslash '/' at the end 
        VITE_BACKEND_API: ${VITE_BACKEND_API}
    container_name: frontend
    ports:
      - "9274:3000"
    depends_on:
      - backend
    restart: always